import { Component, OnInit } from '@angular/core';

// function log(target, name, descriptor) {
//   console.log(target, name, descriptor);

//   //store the original function in variable
//   const original = descriptor.value;
//   //do some manipulations with descriptor.value
//   // descriptor.value = () => {
//   //   console.log('This function was hacked!');
//   // };
//   descriptor.value = function (...args) {
//     console.log('Arguments ', args, ' were passed in this function');
//     const result = original.apply(this, args);
//     console.log('The result of the function is', result);
//   };

//   //return the descriptior
//   return descriptor;
// }

// const log = (className) => {
//   console.log(className);
//   return (...args) => {
//     console.log("Arguments passed to this class's constructor are ", args);
//     return new className(...args);
//   };
// };

// // @log
// class myExampleClass {
//   constructor(arg1, arg2) {
//     console.log('Constructor fired!');
//   }
// }

// const myClass = new myExampleClass(5, 10);

// @Component({
//   selector: 'app-root',
//   templateUrl: './app.component.html',
//   styleUrls: ['./app.component.css'],
// })
// export class AppComponent {
//   text = 'pkik';
//   myVariable = 'app';
//   myDisabledValue = false;
//   constructor() {
//     //One way data binding
//     // this.myVariable = '';
//     // this.myDisabledValue = false;
//     // setInterval(() => {
//     //   this.myVariable = Math.random().toString();
//     //   this.myDisabledValue = Math.random() > 0.5;
//     // }, 500);
//     // console.log(
//     //   //Decorators
//     //   // 'This statement was generated by the constructor',
//     //   // this.aSimpleMethod(5)
//     // );
//   }

//   // Two way databinding
//   updateValue = (e) => {
//     this.text = e.target.value;
//   };

//   callMyFunction = () => {
//     console.log('Funtion called!');
//     this.myDisabledValue = !this.myDisabledValue;
//   };
//   title = 'pkik-app';

//   // @log
//   aSimpleMethod(a) {
//     // console.log('Hey there!');
//     return a * a;
//   }
// }

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  records = {};
  constructor() {}

  ngOnInit() {}
}
